shell:shell.o prompt.o fileOperations.o
	cc shell.o prompt.o fileOperations.o -o shell
shell.o:shell.c
	cc -c shell.c
prompt.o:prompt.c
	cc -c prompt.c
fileOperations.o:fileOperations.c
	cc -c fileOperations.c
